spring:
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://commerce-db:5432/commerce?currentSchema=payment
    username: payment
    password: payment
server:
  port: 0