spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-consumer-group

kafka:
  topics:
    sensor-events: telemetry.sensors.v1
    sensor-snapshot: telemetry.snapshots.v1