spring:
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://commerce-db:5432/commerce?currentSchema=shopping-store
    username: shopping_store
    password: shopping_store
server:
  port: 0